/*
 * sysmem2.c
 *
 *  Created on: Dec 15, 2025
 *      Author: ygultekin
 */
/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>

/**
 * Pointer to the current high watermark of the heap usage
 */
static uint8_t *__sbrk_heap_end = NULL;

void* sysmem_get_sbrk_heap_end(void)
{
    extern uint8_t _end;
    if (__sbrk_heap_end == NULL)
        return (void*)&_end;   // heap not used yet
    return (void*)__sbrk_heap_end;
}

/**
 * @brief _sbrk() allocates memory to the newlib heap and is used by malloc
 *        and others from the C library
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * This implementation starts allocating at the '_end' linker symbol
 * The '_Min_Stack_Size' linker symbol reserves a memory for the MSP stack
 * The implementation considers '_estack' linker symbol to be RAM end
 * NOTE: If the MSP stack, at any point during execution, grows larger than the
 * reserved size, please increase the '_Min_Stack_Size'.
 *
 * @param incr Memory size
 * @return Pointer to allocated memory
 */
void *_sbrk_ramD1(ptrdiff_t incr)
{
  extern uint8_t _end; /* Symbol defined in the linker script */
  extern uint8_t _estack; /* Symbol defined in the linker script */
  extern uint32_t _Min_Stack_Size; /* Symbol defined in the linker script */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;
  const uint8_t *max_heap = (uint8_t *)stack_limit;
  uint8_t *prev_heap_end;

  /* Initialize heap end at first call */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* Protect heap from growing into the reserved MSP stack */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;

  return (void *)prev_heap_end;
}

/**
 * D2 fallback heap (RAM_D2, 0x30000000). Linker'da ._heap_d2 ile reserve edilen
 * 128K'lik bolge. D1 heap istenen boyutu veremedigi anda buradan tahsis edilir.
 */
extern uint8_t _heap_d2_start; /* Symbol defined in the linker script */
extern uint8_t _heap_d2_end;   /* Symbol defined in the linker script */
static uint8_t *__sbrk_heap_d2_end = NULL;

void *_sbrk_ramD2(ptrdiff_t incr)
{
  uint8_t *prev_heap_end;

  /* Initialize D2 heap end at first call */
  if (NULL == __sbrk_heap_d2_end)
  {
    __sbrk_heap_d2_end = &_heap_d2_start;
  }

  /* Protect D2 heap from growing past its reserved region */
  if (__sbrk_heap_d2_end + incr > &_heap_d2_end)
  {
    errno = ENOMEM;
    return (void *)-1;
  }

  prev_heap_end = __sbrk_heap_d2_end;
  __sbrk_heap_d2_end += incr;

  return (void *)prev_heap_end;
}

void* sysmem_get_sbrk_heap_d2_end(void)
{
    if (__sbrk_heap_d2_end == NULL)
        return (void*)&_heap_d2_start;   // D2 fallback heap not used yet
    return (void*)__sbrk_heap_d2_end;
}

/**
 * @brief Iki parcali heap: oncelik D1'de. D1 istenen boyutu veremezse (stack
 *        sinirina dayandiysa) ayni istek butun olarak D2 fallback heap'ten
 *        karsilanir. Tek bir istek iki bolge arasinda BOLUNMEZ.
 */
void *_sbrk(ptrdiff_t incr)
{
  void *p = _sbrk_ramD1(incr);

  if ((void *)-1 == p)
  {
    /* D1 tukendi -> D2'ye tas. D1 denemesinin set ettigi ENOMEM'i temizle. */
    errno = 0;
    p = _sbrk_ramD2(incr);
  }

  return p;
}




